FROM tomcat:9.0.71-jdk11

# 설정 파일 복사
COPY server.xml /usr/local/tomcat/conf
COPY context.xml /usr/local/tomcat/conf

# HTTP, AJP Port
EXPOSE 8080
EXPOSE 8009

# timezone 설정
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 자바 옵션 설정
ENV JAVA_OPTS="-Dspring.profiles.active=dev"

# war 파일 복사
RUN rm -Rf /usr/local/tomcat/webapps/ROOT
COPY build/libs/ROOT.war /usr/local/tomcat/webapps/ROOT.war