apiVersion : apps/v1
kind: Deployment
metadata:
  namespace: tomcat
  name: bunjang
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bunjang
  template:
    metadata:
      labels:
        app: bunjang
    spec:
      containers:
        - name: bunjang 
          image: sorincr.azurecr.io/bunjang:29
          ports:
          - containerPort: 8080
          - containerPort: 8009
      imagePullSecrets:
        - name: sorin-secret
