apiVersion: v1
kind: Service
metadata:
    namespace: tomcat
    name: spring
    labels:
      app: spring
spec:
    type: LoadBalancer
    ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: ajp
        port: 8009
        targetPort: 8009
    selector:
      app: spring